export const seedProfiles = [
  {
    id: "p1",
    name: "Alex",
    age: 15,
    city: "Barcelona",
    bio: "Skate, dibujo y playlists para estudiar. Busco gente chill.",
    interests: ["skate", "arte", "musica", "memes"],
    vibe: "Creativo",
    color: "linear-gradient(135deg, #ff8a65, #ffb74d)",
    contact: { email: "alex@mail.com", instagram: "@alex.skate" },
  },
  {
    id: "p2",
    name: "Lia",
    age: 16,
    city: "Valencia",
    bio: "Me flipa el volley, series y hacer fotos al atardecer.",
    interests: ["deporte", "series", "foto"],
    vibe: "Energetica",
    color: "linear-gradient(135deg, #4dd0e1, #4fc3f7)",
    contact: { email: "lia@mail.com", instagram: "@lia.vibes" },
  },
  {
    id: "p3",
    name: "Nico",
    age: 14,
    city: "Madrid",
    bio: "Jugador de esports, hago edits y necesito duo en Valorant.",
    interests: ["gaming", "edits", "stream"],
    vibe: "Competitivo",
    color: "linear-gradient(135deg, #7986cb, #9575cd)",
    contact: { email: "nico@mail.com", instagram: "@nico.esports" },
  },
  {
    id: "p4",
    name: "Aina",
    age: 17,
    city: "Sevilla",
    bio: "Me gusta escribir historias y escuchar podcasts raros.",
    interests: ["lectura", "podcast", "escritura"],
    vibe: "Calmada",
    color: "linear-gradient(135deg, #81c784, #aed581)",
    contact: { email: "aina@mail.com", instagram: "@aina.escribe" },
  },
  {
    id: "p5",
    name: "Sam",
    age: 15,
    city: "Bilbao",
    bio: "Guitarra, indie y paseos por la ría. Busco banda.",
    interests: ["musica", "guitarra", "indie"],
    vibe: "Artistico",
    color: "linear-gradient(135deg, #ffb74d, #ffd54f)",
    contact: { email: "sam@mail.com", instagram: "@sam.indie" },
  },
  {
    id: "p6",
    name: "Iris",
    age: 16,
    city: "Zaragoza",
    bio: "Fan del cine, hago reseñas y maratones de sagas.",
    interests: ["cine", "reviews", "maraton"],
    vibe: "Curiosa",
    color: "linear-gradient(135deg, #ba68c8, #f06292)",
    contact: { email: "iris@mail.com", instagram: "@iris.cine" },
  },
  {
    id: "p7",
    name: "Leo",
    age: 13,
    city: "Malaga",
    bio: "Amo el basket y los retos creativos en TikTok.",
    interests: ["basket", "reto", "tiktok"],
    vibe: "Divertido",
    color: "linear-gradient(135deg, #4db6ac, #80cbc4)",
    contact: { email: "leo@mail.com", instagram: "@leo.basket" },
  },
  {
    id: "p8",
    name: "Rocio",
    age: 17,
    city: "Alicante",
    bio: "Club de debate, voluntariado y noches de pizza.",
    interests: ["debate", "voluntariado", "pizza"],
    vibe: "Social",
    color: "linear-gradient(135deg, #f48fb1, #f8bbd0)",
    contact: { email: "rocio@mail.com", instagram: "@rocio.debate" },
  },
];

export const safeTips = [
  "No compartas datos personales en el primer chat.",
  "Queda siempre en lugares publicos y con permiso.",
  "Si algo incomoda, bloquea y reporta.",
  "Confia en tu instinto: si algo suena raro, corta.",
];

export const seedUsers = [
  {
    id: "admin-1",
    username: "DaVinci",
    password: "HVitruviano",
    role: "superadmin",
    name: "Super Admin",
    permissions: ["*"],
  },
  {
    id: "admin-2",
    username: "Alpha",
    password: "1234",
    role: "admin",
    name: "Alpha",
    permissions: [],
  },
];
